---
title: 'Relational Attributes for Existing Wind Projects'
author: 'Alessandra Vidal Meza'
date: '`r Sys.Date()`'
---

```{r}
library(here)
library(janitor)
library(tidyverse)
library(sf) # for vector analysis and computation
library(nngeo) # for transmission substation KNN analysis 
```

Load point coordinates of existing wind projects in the U.S.: 
```{r}
# Read tabular data frame
us_pids <- read_csv(here::here('us_PID_cords_PID1335.csv'))
us_pids <- as.data.frame(us_pids) 
# Convert to shapefile data frame with CRS as NAD83
us_pids_geom <- st_as_sf(us_pids, coords = c('lon', 'lat'), crs = 4269)
```

# NREL Cambium Tool
```{r}
# Read tabular data frame
ReEDS <- read_csv(here::here('ReEDS_mapping.csv')) %>%
  rename(pca = r) %>% mutate(pca = as.factor(pca))

# Read vector shapefile data
ReEDS_map <- st_read(here::here('reeds_shapefiles_08032021', 'US_Canada_Map.shp'))
```

```{r}
# Create shapefile data frame
gea_df <- ReEDS_map %>% janitor::clean_names() %>%
  # Convert variable class to factor
  mutate(pca = as.factor(pca)) %>%
  # Keep only PCA regions in GEA regions
  right_join(ReEDS, by = 'pca') %>%
  # Convert variable class to factor
  mutate(gea = as.factor(gea)) %>%
  # Set CRS to NAD83
  st_transform(4269)
```

```{r}
# Set spherical geometry to FALSE
sf_use_s2(FALSE)

# Find GEA regions of the point coordinates, create shapefile data frame
point_cords_gea <- st_join(us_pids_geom, gea_df, join = st_within)

# Keep only columns of interest in shapefile data frame
pids_gea_df <- point_cords_gea %>%
  dplyr::select(PID, t_cap, t_count, t_rd, pca, gea, geometry)

# Check NA values
# pids_gea_df[is.na(pids_gea_df$pca), ]
# Drop PID 1011 and PID 1298 since offshore locations

# Add manually GEA regions to NA values 
pids_gea_df[39, 6] <- 'NEWEc'
pids_gea_df[151, 6] <- 'RFCEc'
pids_gea_df[228, 6] <- 'NYSTc'
pids_gea_df[787, 6] <- 'NYSTc'
pids_gea_df[827, 6] <- 'ERCTc'
```

Save as .csv:
```{r}
pids_gea_df <- pids_gea_df %>%
  mutate(lon = unlist(map(pids_gea_df$geometry, 1)),
         lat = unlist(map(pids_gea_df$geometry, 2))) %>%
  st_drop_geometry()

write.csv(pids_gea_df, here::here('US_pids_GEAs.csv'), row.names = FALSE)
```

# Homeland Infrastructure Foundation-Level Data
```{r}
# Read geodatabase as shapefile data frame
substation <- st_read(here::here('Electric_Substations.gdb')) %>%
  # Set CRS of object to NAD83
  st_transform(4269) %>% 
  # Set CRS of polygon to NAD83
  mutate(SHAPE = SHAPE %>% st_transform(4269)) %>%
  rename(shape = SHAPE) %>%
  # Keep substations with minimum kV condition 
  filter(min_volt >= 115)
```

```{r}
# Find substation observation that is nearest neighbor of each project
substation_join <- st_join(pids_gea_df, substation, 
                           join = st_nn, k = 1, progress = FALSE) %>%
  # Keep only columns of interest
  dplyr::select(PID, id, latitude, longitude, 
                lines, max_volt, min_volt, geometry) %>%
  # Rename variables to common keys
  rename(SID = id, SID_lat = latitude, SID_lon = longitude,
         PID_geom = geometry) %>%
  # Organize in ascending order
  arrange(PID)

# Extract nearest neighbor substation observations (SIDs)
sids <- substation_join %>% 
  # Remove vector geometry 
  st_drop_geometry() %>%
  # Keep only relational keys
  dplyr::select(PID, SID)

# Extract geometries for nearest neighbor substation observations (SIDs)
sids_shapes <- substation %>%
  # Keep only relational key and associated geometry 
  dplyr::select(id, shape) %>% rename(SID = id) %>%
  # Join to nearest neighbor substation observations
  inner_join(sids, by = 'SID') %>%
  # Keep only columns of interest
  dplyr::select(PID, SID, shape) %>%
  # Organize in ascending order
  arrange(PID)

substation_pids <- substation_join %>%
  # Bind geometry column to initial join
  bind_cols(sids_shapes) %>%
  rename(SID_geom = shape,
         PID = PID...1, 
         SID = SID...2) %>% 
  select(-c(PID...9, SID...10, SID_lat, SID_lon))

substation_pids_dist <- substation_pids %>%
  # Compute distance from project to substation geometry in meter and kilometer
  mutate(distance_m = st_distance(PID_geom, SID_geom, by_element = T),
         distance_km = units::set_units(distance_m, 'km')) %>%
  # Remove units
  units::drop_units()

# Extract mean
mean(substation_pids_dist$distance_km)
```

Save as .csv:
```{r}
substation_pids_df <- substation_pids_dist %>%
  st_drop_geometry() %>%
  dplyr::select(-c(SID_geom))

write.csv(substation_pids_df, here::here('substation_pids.csv'), row.names = FALSE)
```
